---
- name: install packages
  hosts: localhost
  remote_user: root
  roles:
    - apt

  tasks:
    - name: Run apt update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Get default packages
      apt:
        name: "{{apt_packages}}"
        state: present

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Visual Studio Code
      snap:
        name: code
        classic: yes
